

create table Currencies
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    varchar,
    full_name varchar,
    sign     varchar
);



create table ExchangeRates
(
    id                 integer generated always as identity
        constraint "ExchangeRates_pk"
            primary key,
    BaseCurrencyId   integer
        constraint "ExchangeRates_pk2"
            unique
        constraint "BaseCurrencyId"
            references Currencies,
    TargetCurrencyId integer
        constraint "ExchangeRates_pk3"
            unique
        constraint "TargetCurrencyId"
            references Currencies,
    Rate             numeric(6)
);


